# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LabThings
description: > # this means to ignore newlines until "baseurl:"
  The open platform for connected laboratory instruments
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://labthings.org" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
include: ['_pages']
exclude:
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-sitemap